CREATE TABLE quests_quizz(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    CATEGORIA VARCHAR(50) NOT NULL ,
    PERGUNTA VARCHAR(200) NOT NULL ,
    OPTION_A VARCHAR(100),
    OPTION_B VARCHAR(100),
    OPTION_C VARCHAR(100),
    OPTION_D VARCHAR(100),
    OPTION_E VARCHAR(100),
    OPTION_F VARCHAR(100),
    OPTION_CORRECT VARCHAR(5),
    VALIDATE_INIT DATETIME,
    VALIDATE_END DATETIME
)